### ISSUE TITLE
Upgrade to ac+ 2.0 API

### ISSUE THREAD

**Issue by benogle** [CentaurWarchief/autocomplete-PHPUnit#7]
One more update! :) There is a 2.0 API that cleans things up and adds a few features. Check it out:

https://github.com/atom/autocomplete-plus/wiki/Provider-API#registering-your-provider-with-autocomplete

By using the 2.0.0 service, you should see deprecations for the changes you need to make. Should be simple. Mostly renaming!

**Comment by CentaurWarchief** [comment]
Umm, sure. Well, `apm publish` works with an existing tag? 'cause I already merged #6 tagging with *1.0.1*.

**Comment by benogle** [comment]
You can just publish another version: `apm publish minor`

**Comment by CentaurWarchief** [comment]
Ya, shipping it now in `v1.0.2`. Well, did it.

**Comment by benogle** [comment]
Now that you're using the 2.0 provider API, there should be deprecations. Check out the status bar for the yellow icon when using the provider.
